version: "3.2"
services:
  web:
    image: "web"
    build:
      context: services/
    ports:
      - "8080:80"
    container_name: php_web
    volumes:
      - ./services/:/var/www/html/
    environment:
      - HOST=${DATABASE_HOST}
      - USERNAME=${DATABASE_USERNAME}
      - PASSWORD=${DATABASE_PASSWORD}
      - NAME=${DATABASE_NAME}
  database:
    image: mysql
    container_name: ${DATABASE_HOST}
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

